services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: swift_user
      POSTGRES_PASSWORD: swift_pass
      POSTGRES_DB: swift_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
