services:
  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://swift_user:swift_pass@postgres:5432/swift_db
      SWIFT_CODES_PATH: /app/app/data/Interns_2025_SWIFT_CODES.xlsx  
    working_dir: /app
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: swift_user
      POSTGRES_PASSWORD: swift_pass
      POSTGRES_DB: swift_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: